# Site settings
title: Upcycles
description: "Boston area cargo framebuilders."
baseurl: ""
url: "http://upcycles.org"
theme: jekyll-theme-leap-day

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Front matter defaults.  Posts use the "post" layout by default, whereas
# everything else uses the "default" layout by default.
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Upcycles"

# Build settings
markdown: kramdown
permalink: pretty
